### ISSUE TITLE
Audio fix

### ISSUE THREAD

**Issue by ghost** [hla63/Msi-modern-15-Hackintosh#1]
You should use [VoodooHDA ](https://sourceforge.net/projects/voodoohda/) instead of AppleALC, I have same specs as you, and it works.

**Comment by gubasbaa** [comment]
i cant boot please help me. sent mail @ nakarin.poonphatthana@gmail.com

**Comment by gubasbaa** [comment]
Please tell to fix step by step 😊

**Comment by hla63** [comment]
Audio works with latest AppleALC [release](https://github.com/acidanthera/AppleALC/releases)
