### ISSUE TITLE
can't boot

### ISSUE THREAD

**Issue by gubasbaa** [hla63/Msi-modern-15-Hackintosh#2]
![ภาพ](https://user-images.githubusercontent.com/68296096/87504813-a2ac9b80-c691-11ea-8780-001b9c33b8e6.png)

please send mail @ Nakarin.poonphatthana@gmail.com

**Comment by hla63** [comment]
Do you have the same cpu proc ?
Core i7 doesn't seem to work.

**Comment by gubasbaa** [comment]
I have msi modern 15 a10m cpu i5 10210u 😂

เมื่อ พ. 15 ก.ค. 2563 เวลา 22:18 hla63 <notifications@github.com> เขียนว่า:

**Comment by gubasbaa** [comment]
now it stuck 
[EB|#LOG:EXITBS:START] 2020-07-15T22:14:54

**Comment by gubasbaa** [comment]
I have msi modern 15 a10m cpu i5 10210u 😂
now it stuck
[EB|#LOG:EXITBS:START] 2020-07-15T22:14:54

**Comment by gubasbaa** [comment]
![image](https://user-images.githubusercontent.com/68296096/87564345-7a9d5680-c6ea-11ea-9a93-8b489be8ca49.jpg)

**Comment by hla63** [comment]
ok same specs ....
I need to upgrade some things in my readme.md cause you had to unlock cfg in bios.
Go to Advanced menu & press the magic combo keys
like [this](https://www.tonymacx86.com/threads/guide-msi-ps63-modern-using-clover-uefi.282632/page-5#post-2031543)

Press ALT + RIGHT-CTRL + RIGHT-SHIFT together then press F2 for see hidden feature
Note (press also fn keys for azerty users)

go to advanced->power & Performance ->CPU - Power Management Control ->CPU lock Configuration ->CFG lock
you need also to disable the secure boot.
You can try this.

**Comment by gubasbaa** [comment]
I cant find >CPU lock Configuration ->CFG lock. In Power Management Control

**Comment by gubasbaa** [comment]
Yes, I try disable CFG lock and disable secure boot. But it still stuck EB:Start

**Comment by gubasbaa** [comment]
Wow , it work perfectly thank you so much. 😂
I try anything but not work.
