### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by AndresGarciaSobrado91** [hla63/Msi-modern-15-Hackintosh#4]
Hi @hla63, I have recently discovered this repo. I have one similar too. Maybe we can help each other if we have issues. Best regards.

https://github.com/AndresGarciaSobrado91/MSI-Modern15-Hackintosh

**Comment by hla63** [comment]
Hi.Thanks you.
I realize that in your repo tpd0.aml is not present and that it is not needed at all. 
Trackpad can works correctly without patch.

Best regards.

**Comment by AndresGarciaSobrado91** [comment]
I realized that HDMI is not working, how did you get it working? Tried with different SMBIOS like MacBookPro16,3 and MacBookPro16,2 with no success. Does your model have a dGPU? Mine is only iGPU

**Comment by hla63** [comment]
Same as yours only igpu.You could try my Device properties for PciRoot(0x0)/Pci(0x2,0x0)


[Device properties.plist.zip](https://github.com/hla63/Msi-modern-15-Hackintosh/files/5533110/Device.properties.plist.zip)

**Comment by AndresGarciaSobrado91** [comment]
Thank you @hla63, that solved the issue. It's working great now. You can delete the pair key-value :

`<key>disable-external-gpu</key>
<data>AQAAAA==</data>`

as it is not needed for our model. Regards.

**Comment by hla63** [comment]
That's right 👀

**Comment by AndresGarciaSobrado91** [comment]
I have just updated to Big Sur and the CPU is overheating when the charger is connected. Are you experiencing this too?

**Comment by hla63** [comment]
I did not make the jump to Big Sur but I think you can try [CPUFriend](https://github.com/acidanthera/CPUFriend/releases)
[OnekeyCpufriend](https://github.com/stevezhengshiqi/one-key-cpufriend) can help you to make CPUFriend data config.

**Comment by AndresGarciaSobrado91** [comment]
Thank you! I think it is solved now with an NVRAM reset after the OSX upgrade

**Comment by AndresGarciaSobrado91** [comment]
About your pull request, backlight keys are working in the same way as before. Now, the power button long press is working but I don't know how does it work. Sometimes, long-press sends the mac to sleep, but sometimes long-press shows a pop up asking if you really want to shut down your Mac. Can you explain to me how does it work?

**Comment by AndresGarciaSobrado91** [comment]
Here, check this device properties. I was having some visual glitches with yours, with this Big Sur is working great:

[Device properties.rtf.zip](https://github.com/hla63/Msi-modern-15-Hackintosh/files/5539950/Device.properties.rtf.zip)

**Comment by hla63** [comment]
Seems to works without problems on Catalina thx.

**Comment by hla63** [comment]
> About your pull request, backlight keys are working in the same way as before. Now, the power button long press is working but I don't know how does it work. Sometimes, long-press sends the mac to sleep, but sometimes long-press shows a pop up asking if you really want to shut down your Mac. Can you explain to me how does it work?

Strange ,power button works like a charms on my laptop.We need to try PWRB.aml or another fix.
[OC little](https://github.com/daliansky/OC-little/tree/master/06-添加缺失的部件)
Thanx google translate !

**Comment by AndresGarciaSobrado91** [comment]
I have been testing the power button and I understood how it works:

-  long-press and release before 4 seconds > sends macOS to sleep. 

- long-press and release after 4 seconds > shows a popup with some power options

- long-press by approx 8 seconds > hard shut down of laptop

Thank u very much!

**Comment by rog22** [comment]
hello @hla63  I have never created a Hackintosh can you help me by explaining what should I do?

**Comment by hla63** [comment]
Best way is to follow the [Dortania guide](https://dortania.github.io/OpenCore-Install-Guide/)
