### ISSUE TITLE
Not an Issue (Help needed with MSI Modern 14 A10M)

### ISSUE THREAD

**Issue by PlessioTihsrah** [hla63/Msi-modern-15-Hackintosh#5]
We both share same hardware. When I tried to use your config (paste everything into EFI folder), I get ACPI Error: Method parse/execution failed.
Can you please tell me what to do, I am a beginner and this is my first time. Thank you
![IMG_20201123_083527674](https://user-images.githubusercontent.com/22316371/100365809-f78bf580-3025-11eb-8c4a-61f08379a376.jpg)

**Comment by hla63** [comment]
Hello seems you don't have exactly the same model
Your trackpad seems to be alps mine is i2C Device.
Try replace VoodooPs2 with this [kext](https://github.com/1Revenger1/VoodooPS2-Alps)

I have the same qd1 error but Mac OS can boot and work without problems.
Please post your unpatched DSDT.

**Comment by PlessioTihsrah** [comment]
[dsdt.zip](https://github.com/hla63/Msi-modern-15-Hackintosh/files/5605966/dsdt.zip)
Here is my DSDT

**Comment by hla63** [comment]
Your Dsdt is very similar like mine except PS2M Device.

Try to find if it's Elan /Synaptics ALPS or another trackpad device with Device manager in windows if you can.
-> https://dortania.github.io/OpenCore-Install-Guide/find-hardware.html#finding-hardware-using-windows
Section # Keyboard, Trackpad and Touchscreen Connection Type

**Comment by PlessioTihsrah** [comment]
I used the guide by dortania, remade all SSDTs and used SSDT-RHUB (read from troubleshooting). Now installer boots fine but hangs when installing. I made recovery only installer from gibmacos and will try to create full installer today.

I am currently using only AWAC, GPI0, PLUG, PNLF-CFL, RHUB, USBX SSDT in ACPI. Do I need anything more?

**Comment by hla63** [comment]
make sure you have the latest bios update installed from [MSI](https://fr.msi.com/product/support_sku/41751#down-bios)

A possible cause of the problem may come from the ssd. If you have the PM981 from samsung, it may cause issues.
[Nvmefix](https://github.com/acidanthera/NVMeFix) can help but it freeze sometimes.

-> https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html

I have another SSD (sabrent) for my Hackintosh partition on the 2nd ssd slot.

**Comment by PlessioTihsrah** [comment]
Yes I have Samsung SSD.
I tried installing on pendrive, it installed and booted successful. Thank you for help.

**Comment by hla63** [comment]
QD1 error could be solved by injecting [RP05.PEGP_SSDT_Patch](https://github.com/navna/msi-modern-15-a10m-acpi/blob/main/RP05.PEGP_SSDT_Patch.dsl)
(Purely cosmetic)
and 
5F514431 to 58514431 _QD1 to XQD1 Rename Patch
5F514435 to 58514435 _QD5 TO XQD5 Rename Patch
