### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by rog22** [hla63/Msi-modern-15-Hackintosh#6]
Please help me I don't know what to do, every time I made this mistake when I start installing Cataline. Did it happen to you?![image](https://user-images.githubusercontent.com/75263525/102000318-9a12cc80-3ce6-11eb-883d-589a760077ae.jpeg)

**Comment by hla63** [comment]
Ocquirks.plist (efi->clover->drivers->UEFI) needs the correct quirks
[quirks](https://github.com/hla63/Msi-modern-15-Hackintosh/blob/master/CLOVER_EFI/EFI/CLOVER/drivers/UEFI/OcQuirks.plist)
